=== guanbg/netdomain/cubism/src/main/resources/service.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="srv" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="defaultlogbefore" type="xs:string"
				use="optional" />
			<xs:attribute name="defaultlogafter" type="xs:string"
				use="optional" />
			<xs:attribute name="datasource" type="xs:string" use="optional"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="srv">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="in" />
				<xs:element ref="sql" />
				<xs:element ref="ref" />
				<xs:element ref="out" />
				<xs:element ref="log" />
				<xs:element ref="exp" />
				<xs:element ref="imp" />
				<xs:element ref="quit" />
				<xs:element ref="data" />
				<xs:element ref="json" />
			</xs:choice>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="extend" type="xs:string" use="optional" />
			<xs:attribute name="datasource" type="xs:string"
				use="optional">
			</xs:attribute>
			<xs:attribute name="auth" type="xs:string" use="optional" />
			<xs:attribute name="scope" use="optional" default="all">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="all" />
						<xs:enumeration value="in" />
						<xs:enumeration value="sql" />
						<xs:enumeration value="ref" />
						<xs:enumeration value="out" />
						<xs:enumeration value="in_out" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="optional" default="local">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="local" />
						<xs:enumeration value="local_report" />
						<xs:enumeration value="remote_jms" />
						<xs:enumeration value="remote_http" />
						<xs:enumeration value="remote_url" />
						<xs:enumeration value="remote_socket" />
						<xs:enumeration value="remote_auto" />
						<xs:enumeration value="webservice" />
						<xs:enumeration value="abstract" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="processor" type="xs:string"
				use="optional" />
			<xs:attribute name="cache" type="xs:string"></xs:attribute>
			<xs:attribute name="updatecache" type="xs:string"></xs:attribute>
			<xs:attribute name="desc" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="data">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="fld" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="stc" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="arr" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:string" use="optional"/>
			<xs:attribute name="filter" type="xs:string" use="optional"/>
			<xs:attribute name="clazz" type="xs:string" use="optional"/>
			<xs:attribute name="json" type="xs:string" use="optional"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="in">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="fld" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="stc" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="arr" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="clazz" type="xs:string" use="optional"/>
			<xs:attribute name="json" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string"
						use="optional" />
					<xs:attribute name="value" type="xs:string"
						use="optional" />
					<xs:attribute name="alwayarray" type="xs:boolean"
						use="optional" />
					<xs:attribute name="lowercase" type="xs:boolean"
						use="optional" />
					<xs:attribute name="generatedkeys" type="xs:string"
						use="optional" />
					<xs:attribute name="each" type="xs:string"
						use="optional" />
					<xs:attribute name="condition" type="xs:string"
						use="optional" />
					<xs:attribute name="errorcode" type="xs:string"
						use="optional" />
					<xs:attribute name="errormsg" type="xs:string"
						use="optional" />
					<xs:attribute name="cache" type="xs:string">
					</xs:attribute>
					<xs:attribute name="updatecache"
						type="xs:string">
					</xs:attribute>
					<xs:attribute name="desc" type="xs:string"
						use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="srv" type="xs:string" use="optional"/>
					<xs:attribute name="clazz" type="xs:string" use="optional"/>
					<xs:attribute name="each" type="xs:string" use="optional"/>
					<xs:attribute name="condition" type="xs:string" use="optional"/>
					<xs:attribute name="errorcode" type="xs:string" use="optional"/>
					<xs:attribute name="errormsg" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="out">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="fld"/>
				<xs:element ref="stc"/>
				<xs:element ref="arr"/>
			</xs:choice>
			<xs:attribute name="clazz" type="xs:string" use="optional"/>
			<xs:attribute name="json" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="fld">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="value" type="xs:string" use="optional"/>
					<xs:attribute name="type" type="xs:string" use="optional"/>
					<xs:attribute name="format" type="xs:string" use="optional"/>
					<xs:attribute name="required" type="xs:boolean" use="optional" default="false"/>
					<xs:attribute name="check" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="stc">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="fld"/>
				<xs:element ref="stc"/>
				<xs:element ref="arr"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="arr">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="stc"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="log">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="fld"/>
				<xs:element ref="row"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="before" type="xs:string" use="optional"/>
			<xs:attribute name="after" type="xs:string" use="optional"/>
			<xs:attribute name="condition" type="xs:string" use="optional"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="row">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="fld"/>
			</xs:sequence>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>	
	<xs:element name="quit">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="optional" default="faild">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="faild"/>
								<xs:enumeration value="successful"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="condition" type="xs:string" use="optional"/>
					<xs:attribute name="errorcode" type="xs:string" use="optional"/>
					<xs:attribute name="errormsg" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="json">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="value" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="exp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="value" type="xs:string" use="optional"/>
					<xs:attribute name="processor" type="xs:string" use="required"/>
					<xs:attribute name="fetch" type="xs:int" use="optional" default="20"/>
					<xs:attribute name="each" type="xs:string" use="optional"/>
					<xs:attribute name="async" type="xs:boolean" use="optional" default="true"/>
					<xs:attribute name="condition" type="xs:string" use="optional"/>
					<xs:attribute name="errorcode" type="xs:string" use="optional"/>
					<xs:attribute name="errormsg" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="imp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="value" type="xs:string" use="optional"/>
					<xs:attribute name="processor" type="xs:boolean" use="required"/>
					<xs:attribute name="fetch" type="xs:int" use="optional"  default="20"/>
					<xs:attribute name="each" type="xs:string" use="optional"/>
					<xs:attribute name="async" type="xs:boolean" use="optional" default="true"/>
					<xs:attribute name="condition" type="xs:string" use="optional"/>
					<xs:attribute name="errorcode" type="xs:string" use="optional"/>
					<xs:attribute name="errormsg" type="xs:string" use="optional"/>
					<xs:attribute name="desc" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== guanbg/netdomain/front/WEB-INF/service/service-version.xml
<?xml version="1.0" encoding="UTF-8"?>
<service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="service.xsd" 
	defaultlogbefore="sys.log.before" defaultlogafter="sys.log.after">
	
	<!-- 测试**************************************************************************************************************** -->
		
	<srv id="version.query" desc="版本信息">
		<sql id="version" errorcode="10012" alwayarray="true" errormsg="查询账户信息失败"><![CDATA[
			 select * from fms_version where version_num='#{in.version_num}' and version_name='#{in.version_name}' and version_memo='#{in.version_memo}' and is_current='#{in.is_current}' and create_date='#{in.create_date}' and create_user='#{in.create_user}' and last_date='#{in.last_date}' and last_user='#{in.last_user}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="rows" value="version" />
			<fld name="pageSize">pagehead.pagecount</fld>
			<fld name="page">pagehead.currentpage</fld>
			<fld name="total">pagehead.totalpage</fld>
			<fld name="records">pagehead.totalrecord</fld>
		</out>
	</srv>
	
	<srv id="version.add" desc="新建版本信息">
		<sql id="insert" errorcode="10012" errormsg="新增用户失败，输入数据错误，请确认"><![CDATA[
			insert into fms_version(version_num,version_name,version_memo,is_current,create_date,create_user,last_date,last_user) 
			values 
			('#{in.version_num}','#{in.version_name}','#{in.version_memo}','#{in.is_current}',NOW(),'#{in.syshead.userid}','#{in.last_date}','#{in.last_user}')
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
	
	<srv id="version.update" desc="修改版本信息">
	<quit condition="get('in.version_num')==null or get('in.version_num').isEmpty()" errorcode="10011" errormsg="修改失败，上送数据不正确,请重试"/>
		<sql id="id" value="select * from fms_version where version_num='#{in.version_num}'" />
		<quit condition="get('in.version_num')==null or get('in.version_num').isEmpty()" errorcode="10011" errormsg="修改失败，上送数据不正确,请重试"/>
		
		<sql id="select" value="update fms_version set version_name='#{in.version_name}',version_memo='#{in.version_memo}', is_current='#{in.is_current}',create_date='#{in.create_date}',create_user='#{in.create_user}',last_date=NOW(),last_user='#{in.syshead.userid}' where version_num='#{in.version_num}'" />
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
	
	<srv id="version.select" desc="修改查询版本信息">
		
		<quit condition="get('in.id')==null or get('in.id').isEmpty()" errorcode="10011" errormsg="查询失败，上送数据不正确,请重试"/>
		<sql id="version" value="select * from fms_version where version_num='#{in.id}'" />
	<out>
			<stc name="rethead" value="rethead" />
			<stc name="version" value="version" />
		</out>
	</srv>
	
	<srv id="version.delete" desc="删除版本">
		<quit condition="get('in.id')==null or get('in.id').isEmpty()" errorcode="10011" errormsg="删除版本失败，上送数据不正确,请重试"/>
		<sql id="delete" value="delete from fms_version where version_num='#{in.id}'"/>
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
	
</service>

=== guanbg/netdomain/front/WEB-INF/service/service-plist.xml
<?xml version="1.0" encoding="UTF-8"?>
<service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="service.xsd">

	<srv id="pklist.sys_data_dictionary" desc="单级">
		<sql id="pklist"  alwayarray="true" value="SELECT datavalue VALUE, CASE disptype WHEN 1 THEN concat(datavalue,'-',dataname) ELSE dataname END TEXT, extenddata, description FROM sys_data_dictionary WHERE parentid IN (SELECT id FROM sys_data_dictionary WHERE datavalue='#{in.datavalue}') ORDER BY disporder,datavalue" />
	</srv>
	<srv id="pklist.sys_data_dictionary.extend" desc="两级">
		<sql id="pklist"  alwayarray="true" value="SELECT concat(datavalue,'-',extenddata) VALUE, CASE disptype WHEN 1 THEN concat(datavalue,'-',dataname) ELSE dataname END TEXT, extenddata, description FROM sys_data_dictionary WHERE parentid IN (SELECT id FROM sys_data_dictionary WHERE datavalue='#{in.datavalue}') ORDER BY disporder,datavalue" />
	</srv>
	
	<srv id="pklist.sys_data_dictionary_professional_list" desc="查询企业资料员专业分类">
		<sql id="crop"><![CDATA[
			SELECT professional_list FROM fms_contractor_basicinfo WHERE contractor_id='#{in.contractor_id}'
		]]></sql>
		<sql id="pklist" alwayarray="true"><![CDATA[
			 SELECT datavalue VALUE, CASE disptype WHEN 1 THEN concat(datavalue,'-',dataname) ELSE dataname END TEXT, extenddata, description 
			 FROM sys_data_dictionary 
			 WHERE parentid IN (SELECT id FROM sys_data_dictionary WHERE datavalue='professional_list') AND datavalue IN(#{crop.professional_list}) 
			 ORDER BY disporder,datavalue
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="pklist" value="pklist" />
		</out>
	</srv>
	
	<srv id="pklist.sys_departments">
		<sql id="pklist"  alwayarray="true" value="SELECT id VALUE, departmentname TEXT FROM sys_departments ORDER BY disporder,id" />
	</srv>
	<srv id="pklist.sys_groups">
		<sql id="pklist"  alwayarray="true" value="SELECT id VALUE, groupname TEXT FROM sys_groups ORDER BY groupname,id" />
	</srv>
	<srv id="pklist.sys_area_province">
		<sql id="pklist"  alwayarray="true" value="select areacode value, areaname text from sys_areas where parentid is null order by areaorder,id" />
	</srv>
	<srv id="pklist.sys_area_city_region.byareacode">
		<sql id="pklist"  alwayarray="true" value="select areacode value, areaname text from sys_areas where parentid in (select id from sys_areas where areacode='#{in.areacode}') order by areaorder,id" />
	</srv>
	<srv id="pklist.fms_version">
		<sql id="pklist"  alwayarray="true" value="SELECT version_id VALUE, concat(version_num,'-',version_name) TEXT FROM fms_version WHERE is_current=1 ORDER BY create_date desc" />
	</srv>
	
	<srv id="pklist.contractor_basicinfo">
		<sql id="pklist"  alwayarray="true" value="SELECT contractor_id VALUE, company_name TEXT FROM fms_contractor_basicinfo WHERE contractor_id in (select contractor_id from fms_contractor_user where user_id='#{in.syshead.userid}') or contractor_id in (select contractor_id from fms_contractor_documentor where documentor_ID in (select documentor_id from fms_contractor_user where user_id='#{in.syshead.userid}'))" />
	</srv>
	
	<srv id="pklist.fms_config.version">
		<sql id="pklist"  alwayarray="true" value="SELECT id VALUE, concat(code,'-',name) TEXT FROM fms_config WHERE nodetype=1 and parentid='#{in.id}'" />
	</srv>
	
	<srv id="pklist.fms_businessrule" desc="业务规则版本列表">
		<sql id="pklist"  alwayarray="true" value="SELECT ruleid VALUE, concat(rulename,'-',ruleversion) TEXT FROM fms_businessrule WHERE status='1' ORDER BY rulename,ruleversion" />
	</srv>
	<srv id="pklist.fms_config_version" desc="业务规则列表">
		<sql id="pklist"  alwayarray="true" value="SELECT param_version_id VALUE, concat(version_num,'-',version_name) TEXT FROM fms_config_version WHERE IFNULL(version_status,0)='0' ORDER BY disp_order,last_date desc,create_date desc" />
	</srv>
</service>

=== guanbg/netdomain/front/WEB-INF/service/service-sysmsg.xml
<?xml version="1.0" encoding="UTF-8"?>
<service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="service.xsd" 
	defaultlogbefore="sys.log.before" defaultlogafter="sys.log.after">
	<srv id="msg.query" desc="消息信息">
		<sql id="msg" alwayarray="true" errorcode="10012" errormsg="查询消息信息失败"><![CDATA[
			 select *
			 ,(select count(receive_id) from sys_msg_receive WHERE msg_id=a.msg_id and read_time is null) count_send
		     ,(select count(receive_id) from sys_msg_receive WHERE msg_id=a.msg_id  and read_time is not null) count_read
			 from sys_msg a where 
			 msg_id='#{in.msg_id}' and 
			 send_user='#{in.syshead.userid}' and 
			 msg_title='#{in.msg_title}' and 
			 msg_text='#{in.msg_text}' and 
			 attechment='#{in.attechment}' and 
			 send_time='#{in.send_time}' and 
			 msg_status='#{in.msg_status}'
			 order by msg_id desc
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="rows" value="msg" />
			<fld name="pageSize">pagehead.pagecount</fld>
			<fld name="page">pagehead.currentpage</fld>
			<fld name="total">pagehead.totalpage</fld>
			<fld name="records">pagehead.totalrecord</fld>
		</out>
	</srv>
	
	<srv id="msg.querybyuser" desc="参建单位收到的消息">
		<sql id="msg" alwayarray="true" errorcode="10012" errormsg="查询消息信息失败"><![CDATA[
			select a.msg_id,b.receive_id,b.read_time,
			(select username FROM sys_users  WHERE ID=a.send_user) send_user_name,
			a.send_user,a.msg_title,a.msg_text,
			date_format(a.send_time,'%Y-%m-%d %H:%I:%S') send_time 
			from sys_msg a 
			left outer join sys_msg_receive b
			on a.msg_id=b.msg_id
			where b.receive_user = '#{in.contractor_id}' and
			a.msg_status=2
			order by a.msg_id desc
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="rows" value="msg" />
		</out>
	</srv>
	
	<srv id="msg.updbyuser" desc="参建单位阅读消息">
		<sql id="msg" alwayarray="true" errorcode="10012" errormsg="查询消息信息失败SSS"><![CDATA[
			update sys_msg_receive
			set read_time = now()
			where receive_id = '#{in.receive_id}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="rows" value="msg" />
		</out>
	</srv>
	
	<srv id="msg.add" desc="新建消息">
		<ref id="msg_id" clazz="com.platform.cubism.util.StringUtils.getUUID()"/>
		<sql id="msg_add" generatedkeys="msg_id" errorcode="10012" errormsg="新增消息失败，输入数据错误，请确认"><![CDATA[
			insert into sys_msg
			(send_user,msg_title,msg_text,attechment,send_time,msg_status) 
			values 
			('#{in.syshead.userid}','#{in.msg_title}','@{in.msg_text}','#{in.attechment}',now(),'#{in.msg_status}')
		]]></sql>
		<sql id="msg_receive_add" condition="get('in.receive_user_ids')!=null and get('in.receive_user_ids').getStringValues(',')!='0' and !get('in.receive_user_ids').getStringValues(',').contains('0,')"><![CDATA[
			insert into sys_msg_receive(receive_user,msg_id)
			values
			('#{in.receive_user_ids}','#{msg_add.msg_id}')
		]]></sql>
		<sql id="msg_receive_add" condition="get('in.receive_user_ids')!=null and (get('in.receive_user_ids').getStringValues(',')=='0' or get('in.receive_user_ids').getStringValues(',').contains('0,'))"><![CDATA[
			insert into sys_msg_receive(receive_user,msg_id)
			select contractor_id,'#{msg_add.msg_id}' msg_id
			from fms_contractor_basicinfo
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
	
	<srv id="msg.update" desc="修改信息">
		<quit condition="get('in.msg_id')==null or get('in.msg_id').isEmpty()" errorcode="10011" errormsg="查询失败，上送数据不正确,请重试"/>
		
		<sql id="msg_upd" errorcode="10012" errormsg="操作失败，输入数据错误，请确认"><![CDATA[
			update sys_msg 
			set 
			msg_title='#{in.msg_title}',
			msg_text='@{in.msg_text}',
			msg_status = '#{in.msg_status}'
			where msg_id = '#{in.msg_id}'
		]]></sql>
		<sql id="msg_receive_del" ><![CDATA[
			delete from sys_msg_receive
			where msg_id = '#{in.msg_id}'
		]]></sql>
		<sql id="msg_receive_add" ><![CDATA[
			insert into sys_msg_receive(receive_user,msg_id)
			values
			('#{in.receive_user_ids}','#{in.msg_id}')
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
	
	<srv id="msg.select" desc="修改查询信息">
		<quit condition="get('in.msg_id')==null or get('in.msg_id').isEmpty()" errorcode="10011" errormsg="查询失败，上送数据不正确,请重试"/>
		<sql id="msg_upd" errorcode="10012" errormsg="操作失败，输入数据错误，请确认"><![CDATA[
			select *,
			(select group_concat(receive_user) from sys_msg_receive where msg_id=a.msg_id) receive_user_ids,
			(select group_concat(company_name) from fms_contractor_basicinfo where contractor_id in(select receive_user from sys_msg_receive where msg_id=a.msg_id)) receive_user_names
			from sys_msg a where msg_id='#{in.msg_id}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<stc name="msg_upd" value="msg_upd" />
		</out>
	</srv>
	
	<srv id="msg.selectandlook" desc="查询消息和阅读情况">
		<quit condition="get('in.msg_id')==null or get('in.msg_id').isEmpty()" errorcode="10011" errormsg="查询失败，上送数据不正确,请重试"/>
		<sql id="msg_upd" errorcode="10012" errormsg="操作失败，输入数据错误，请确认"><![CDATA[
			select *,
			(select group_concat(receive_user) from sys_msg_receive where msg_id=a.msg_id) receive_user_ids,
			(select group_concat(company_name) from fms_contractor_basicinfo where contractor_id in(select receive_user from sys_msg_receive where msg_id=a.msg_id)) receive_user_names
			,(select COUNT(receive_id) FROM sys_msg_receive WHERE msg_id=a.msg_id AND read_time is null) count_send
		    ,(select COUNT(receive_id) FROM sys_msg_receive WHERE msg_id=a.msg_id  AND read_time is not null) count_read
		     ,(SELECT GROUP_CONCAT(company_name) FROM fms_contractor_basicinfo WHERE contractor_id IN(SELECT receive_user FROM sys_msg_receive WHERE msg_id=a.msg_id AND read_time IS  NULL)) receive_user_names_send 
		    ,(SELECT GROUP_CONCAT(company_name) FROM fms_contractor_basicinfo WHERE contractor_id IN(SELECT receive_user FROM sys_msg_receive WHERE msg_id=a.msg_id AND read_time IS NOT  NULL)) receive_user_names_read
			from sys_msg a where msg_id='#{in.msg_id}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<stc name="msg_upd" value="msg_upd" />
		</out>
	</srv>
	
	<srv id="msg.selectandlookhistory" desc="查询消息和阅读历史情况">
		<quit condition="get('in.msg_id')==null or get('in.msg_id').isEmpty()" errorcode="10011" errormsg="查询失败，上送数据不正确,请重试"/>
		<sql id="msg_upd" alwayarray="true" errorcode="10012" errormsg="操作失败，输入数据错误，请确认"><![CDATA[
			select a.msg_id,receive_id,a.receive_user,b.company_name,read_time from sys_msg_receive a
			left outer join fms_contractor_basicinfo b 
			on a.receive_user = b.contractor_id
			where a.msg_id ='#{in.msg_id}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
			<arr name="rows" value="msg_upd" />
		</out>
	</srv>
	
	<srv id="msg.delete" desc="删除信息">
		<quit condition="get('in.id')==null or get('in.id').isEmpty()" errorcode="10011" errormsg="删除信息失败，上送数据不正确,请重试"/>
		<sql id="msg">
		<![CDATA[
			delete from sys_msg where msg_id='#{in.id}'
		]]></sql>
		<out>
			<stc name="rethead" value="rethead" />
		</out>
	</srv>
</service>
