=== guanbg/netdomain/front/WEB-INF/query/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="query">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="qry" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="qry">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fld" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="srvid" type="xs:string" use="required" />
			<xs:attribute name="desc" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="fld">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="required" />
					<xs:attribute name="text" type="xs:string" use="required" />
					<xs:attribute name="type" use="optional" default="string">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="string" />
								<xs:enumeration value="number" />
								<xs:enumeration value="date" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="data" type="xs:string" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== guanbg/netdomain/front/WEB-INF/query/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="query.xsd">
	<qry id="queryuser" srvid="sys.queryuser" desc="用户信息综合查询">
		<fld id="userid" text="登录名称"/>
		<fld id="username" text="用户简称"/>
		<fld id="departmentid" text="隶属部门" type="number" data="plist.departmentlist"/>
	</qry>
	<qry id="b" srvid="sys.queryuser2" desc="测试">
		<fld id="e1" text="e1" type="number"/>
		<fld id="e2" text="e2" type="date">"jsondata"</fld>
	</qry>
</query>
